// <auto-generated />
namespace Outfit_Picker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixoutfits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixoutfits));
        
        string IMigrationMetadata.Id
        {
            get { return "201609272354431_fix-outfits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
